name: Build

on:
  push:
    branches: ['main']

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  macos-universal-build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Upgrade CMake
        run: |
          brew update
          brew install cmake
          cmake --version

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -G "Xcode"

      - name: Build
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: setekh-macos
          path: |
            ./build/Setekh_artefacts/Release/LV2
            ./build/Setekh_artefacts/Release/AU
            ./build/Setekh_artefacts/Release/VST3
            ./build/Setekh_artefacts/Release/readme.txt
            !./build/Setekh_artefacts/Release/VST3/*.exp
            !./build/Setekh_artefacts/Release/VST3/*.lib
